language: php

php:
  - '7.0.8'
services:
  - mysql
before_install:
  - cp .env.example .env
  - sed -i 's/DATABASE=homestead/DATABASE=room/' .env
  - sed -i 's/USERNAME=homestead/USERNAME=root/' .env
  - sed -i 's/PASSWORD=secret/PASSWORD=secret/' .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS room;'
install:
  # Install dev php dependencies
  - composer install --no-interaction --prefer-dist
script:
  # Generate Key
  - sh -c "php artisan key:generate"
  # Refresh Migrations
  - sh -c "php artisan migrate:refresh --seed"
  # Run tests
  - sh -c "vendor/bin/phpunit"
