version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www/html
    links:
      - db
      - cache
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - REDIS_PORT=6379
      - REDIS_HOST=cache
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=room
    ports:
      - "33061:3306"
  cache:
    image: redis:3.0
    ports:
       - "63791:6379"
